version: '3.8'
services:
  app:
    image: vinuthsriarampath/tuitiontoall:2.1.0
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://db:3306/tuitiontoall_v2
      - DB_USERNAME=root
      - DB_PWD=password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=tuitiontoall_v2
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$DB_PWD"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:

networks:
  app-network: