spring:
  application:
    name: TuitionToAll-V2

  datasource:
    url: ${DB_URL}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PWD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

