name: CI/CD pipeline

on:
  pull_request:
    branches:
      - release/production
  push:
    branches:
      - release/production
    tags:
      - 'v*.*.*'
env:
  JAVA_VERSION: 22
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

