name: CI/CD pipeline

on:
  pull_request:
    branches:
      - release/production
  push:
    branches:
      - release/production
    tags:
      - 'v*.*.*'

env:
  JAVA_VERSION: 22
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Extract Project Version
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "PROJECT_VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "TAG_VERSION=v$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Find JAR file
        id: find_jar
        run: |
          JAR_PATH=$(find target -name "*.jar" | grep -v "original")
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}
            ghcr.io/${{ env.REPO_NAME }}
          tags: |
            type=raw,value=${{ steps.get_version.outputs.PROJECT_VERSION }}
            type=sha

      - name: Convert repository name to lowercase
        run: echo "REPO_NAME=$(echo '${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV


      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ steps.get_version.outputs.PROJECT_VERSION }}
            ghcr.io/${{ github.actor }}/${{ env.REPO_NAME }}:${{ steps.get_version.outputs.PROJECT_VERSION }}
          build-args: |
            JAR_FILE=${{ steps.find_jar.outputs.JAR_PATH }}

      - name: Publish Docker Package
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ steps.get_version.outputs.PROJECT_VERSION }}
          docker push ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.PROJECT_VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.TAG_VERSION }}
          name: Release ${{ steps.get_version.outputs.PROJECT_VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            ${{ steps.find_jar.outputs.JAR_PATH }}
